GET http://localhost:8080/demo/api/entity
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/demo/api/entity/2
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/demo/api/entity/2/data?data_param=somedata
Accept: */*
Cache-Control: no-cache

###