GET http://localhost:8080/demo/api/entity
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/demo/api/entity
Accept: */*
Cache-Control: no-cache
Mock: demoservice/error
Mock-Timeout: demoservice/1000

###

GET http://localhost:8080/demo/api/entity/2
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/demo/api/entity/filter?a=aaa&b=bbb
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/demo/api/entity HTTP/1.1
Content-Type: application/json

{ "name": "arbitrary name" }

###