server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    ROOT: ${ROOT_LOGGING_LEVEL:INFO}
    com.mockachu: ${LOGGING_LEVEL:INFO}
    org.springframework.boot.SpringApplication: INFO

spring:
  application:
    name: Mockachu

  main:
    banner-mode: LOG

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config-filename: ${CONFIG_FILENAME:.\config.yml}
  config-backup-filename: ${CONFIG_BACKUP_FILENAME:.\config-backup.yml}
  soap-error-data-file: soapFault.xml
  client:
    max-connections: ${MAX_CONNECTIONS:2000}
    max-pending: ${MAX_PENDING:2000}
  mock-service:
    cache-size: ${MOCK_CACHE_SIZE:1000}
  request-service:
    cache-size: ${REQUEST_CACHE_SIZE:1000}
  test-service:
    cache-size: ${TEST_CACHE_SIZE:2000}
